package Bliblioteca;

public enum Tematica {
    GENERALIDADES, FILOSOFIA_Y_PSICOLOGIA, RELIGION, CIENCIAS_SOCIALES, LENGUAS, CIENCIA_MATEMATICA, TECNOLOGIA, ARTES, LITERATURA_Y_RETORICA, GEOGRAFIA_Y_HISTORIA

}
